/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.QL_TaiKhoanDAO;
import javax.swing.JOptionPane;
import view.GameFrame;

/**
 *
 * @author thung
 */
public class NguoiDung extends javax.swing.JFrame {

    GameFrame gameframe;
    
    
    /**
     * Creates new form NguoiDung
     */
    public NguoiDung() {
        initComponents();
        txt_ten_tk.setText("user: "+QL_TaiKhoanDAO.layTenTK());
                this.setLocationRelativeTo(null);


  
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        btn_de = new javax.swing.JButton();
        btn_tb = new javax.swing.JButton();
        btn_kho = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_ten_tk = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuDangNhap = new javax.swing.JMenuItem();
        Menu_Thoat = new javax.swing.JMenuItem();
        btn_bxh = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btn_xem = new javax.swing.JMenuItem();

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btn_de.setBackground(getBackground());
        btn_de.setText("Dễ");
        btn_de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deActionPerformed(evt);
            }
        });

        btn_tb.setBackground(getBackground());
        btn_tb.setText("Trung Bình");
        btn_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tbActionPerformed(evt);
            }
        });

        btn_kho.setBackground(getBackground());
        btn_kho.setText("Khó");
        btn_kho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_khoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("DÒ MÌN");

        txt_ten_tk.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt_ten_tk.setText("user");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_de)
                    .addComponent(btn_tb)
                    .addComponent(btn_kho))
                .addGap(216, 216, 216))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txt_ten_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_de, btn_kho, btn_tb});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_ten_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(btn_de)
                .addGap(18, 18, 18)
                .addComponent(btn_tb)
                .addGap(18, 18, 18)
                .addComponent(btn_kho)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jMenu1.setText("Hệ thống");

        mnuDangNhap.setText("Đăng xuất");
        mnuDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDangNhapActionPerformed(evt);
            }
        });
        jMenu1.add(mnuDangNhap);

        Menu_Thoat.setText("Thoát");
        Menu_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ThoatActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_Thoat);

        jMenuBar1.add(jMenu1);

        btn_bxh.setText("BXH");
        btn_bxh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bxhActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Xem");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        btn_bxh.add(jMenuItem4);

        jMenuBar1.add(btn_bxh);

        jMenu4.setText("Hướng Dẫn");

        btn_xem.setText("Xem");
        btn_xem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xemActionPerformed(evt);
            }
        });
        jMenu4.add(btn_xem);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deActionPerformed
        // TODO add your handling code here:
        QL_TaiKhoanDAO.capNhatTrangThaiOnGame(1,"On");
        gameframe = new GameFrame(8, 8, 10);
        gameframe.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_deActionPerformed

    private void btn_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tbActionPerformed
        // TODO add your handling code here:
        QL_TaiKhoanDAO.capNhatTrangThaiOnGame(2,"On");
        gameframe = new GameFrame(16, 16, 40);
        gameframe.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_tbActionPerformed

    private void btn_khoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_khoActionPerformed
        // TODO add your handling code here:
        QL_TaiKhoanDAO.capNhatTrangThaiOnGame(3,"On");
        gameframe = new GameFrame(16, 30, 99);
        gameframe.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_khoActionPerformed

    private void btn_bxhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bxhActionPerformed
        // TODO add your handling code here:
        
        BXH bxh =  new BXH();
        bxh.setVisible(true);
        
        // Đóng JFrame1 nếu cần thiết
        this.dispose();
    }//GEN-LAST:event_btn_bxhActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        BXH bxh =  new BXH();
        bxh.setVisible(true);
        
        // Đóng JFrame1 nếu cần thiết
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btn_xemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xemActionPerformed
        // TODO add your handling code here:
             HD_GUI hd_gui = new HD_GUI();
            hd_gui.setVisible(true);
            this.dispose();
        
    }//GEN-LAST:event_btn_xemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Bạn có muốn đóng cửa sổ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
                
                if (result == JOptionPane.YES_OPTION) {
                    QL_TaiKhoanDAO.capNhatTrangThai(QL_TaiKhoanDAO.layTenTK(),"Off");
                    
                    System.exit(0);
                    
                }
    }//GEN-LAST:event_formWindowClosing

    private void mnuDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDangNhapActionPerformed
            QL_TaiKhoanDAO.capNhatTrangThai(QL_TaiKhoanDAO.layTenTK(),"Off");
        DangNhap_GUI  frmDN = new DangNhap_GUI();
         frmDN.setVisible(true);
         this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_mnuDangNhapActionPerformed

    private void Menu_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ThoatActionPerformed
        // TODO add your handling code here:
                int result = JOptionPane.showConfirmDialog(this, "Bạn có muốn đóng cửa sổ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
                
                if (result == JOptionPane.YES_OPTION) {
                    QL_TaiKhoanDAO.capNhatTrangThai(QL_TaiKhoanDAO.layTenTK(),"Off");
                    
                    System.exit(0);
                    
                }
    }//GEN-LAST:event_Menu_ThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
                new NguoiDung().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menu_Thoat;
    private javax.swing.JMenu btn_bxh;
    private javax.swing.JButton btn_de;
    private javax.swing.JButton btn_kho;
    private javax.swing.JButton btn_tb;
    private javax.swing.JMenuItem btn_xem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mnuDangNhap;
    private javax.swing.JLabel txt_ten_tk;
    // End of variables declaration//GEN-END:variables
}
